#!/usr/bin/env python3
"""Community notes: what the field already knows about a vessel we run.

Commissioned by the operator 2026-08-04, after a week in which this fabric
rediscovered several things the field had already written down. His framing:
every new finding that is a rehash of someone else's old finding is drain on a
tokenized system, and at least one token generator here is metered. Not fatal on
its face, but we should stop recreating the wheel.

WHAT THIS IS NOT. It is not a general answer to token burn, and it should not be
judged as one. Almost everything expensive this week was about OUR system and
OUR data: four undecoded PDFs poisoning an anchor set, a repo-shaped migration
blind to gitignored rooms, a reconciler scoped out of the room it was built for.
None of that has an upstream. The value here is concentrated in one class,
vessel behavioural quirks and known defects, and that class is real: the
max_tokens-eaten-by-reasoning trap cost three separate mistakes in two days and
is discussed openly upstream.

THE SECOND BENEFIT IS PROBABLY THE LARGER ONE. The E4B investigation was not
expensive because the answer was unavailable; it was expensive because the
hypothesis space had to be built from nothing. Having the known failure modes in
front of you changes what you test first.

AND IT RUNS BOTH WAYS. The operator's standing rule is to search the field
before claiming a finding and to contribute back where our setup provides a
control others cannot run. That rule currently depends on somebody remembering.
A dossier makes it structural, and every dossier carries a FOR UPSTREAM section
for what we know that the field does not.

DESIGN RULES.

1. Titles are the product. A title plus state, age and comment count is enough
   to decide whether to care, and 45 of them cost about 600 tokens. Full comment
   bodies cost a hundred times that and are mostly noise. Bodies are fetched on
   demand with --thread, never in bulk.
2. Read on demand, never at boot. A dossier hydrated every session costs tokens
   every session for value needed occasionally.
3. Sources are tiered by measured signal, not by guess. See sources.toml.
4. Never scrape around a gate. Doc sites are probed for llms-full.txt and
   llms.txt; if neither exists the source is declined and said so.
5. Authored text is never clobbered. Everything outside the generated block is
   preserved across regeneration, because a lab note is the one thing here that
   cannot be re-fetched.
6. Polite. ETags where the API honours them, one pass, no retry storms. This
   fleet has been IP banned by a scholarly API for being impolite before.

Usage:
  community.py collect [--model KEY]     refresh dossiers from upstream
  community.py stub                      write pointer stubs beside the weights
  community.py thread <src> <id>         fetch one discussion or issue body

Floor: DMF. No em dashes, no ellipses.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCES = HERE / "sources.toml"
WATCHLIST = HERE / "watchlist.toml"
DOSSIERS = HERE / "dossiers"
STATE = HERE / "community_state.json"

HF_API = "https://huggingface.co/api"
UA = "model-card-community/1 (+local instrument, one pass, no crawl)"

GEN_BEGIN = "<!-- COMMUNITY:BEGIN generated by community.py, edits here are lost -->"
GEN_END = "<!-- COMMUNITY:END -->"

TEMPLATE = """# {model}: community notes and lab documentation

Local documentation for a vessel this fabric serves, beside what the field has
already written about it. Generated half is refreshed by
`tools/zoo/community.py collect`; everything outside the generated block is
hand-written and preserved.

Floor: DMF. No em dashes, no ellipses.

## Lab notes, ours

_Nothing recorded yet. Put what we have learned running this vessel here:
settings that matter, failures we have hit, the configuration it actually wants._

## For upstream

_What we know that the field does not. The standing rule is to contribute back
where our setup provides a control others cannot run. Nothing queued yet._

{generated}
"""


def get_json(url, headers=None, timeout=30):
    req = urllib.request.Request(url, headers={"User-Agent": UA, **(headers or {})})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return json.loads(r.read().decode(errors="replace")), r.status
    except urllib.error.HTTPError as e:
        return None, e.code
    except Exception:
        return None, 0


def gh(path, timeout=45):
    """GitHub through the gh CLI, so its auth and 5000/hr limit are inherited."""
    try:
        p = subprocess.run(["gh", "api", path], capture_output=True,
                           text=True, timeout=timeout)
        if p.returncode != 0:
            return None
        return json.loads(p.stdout)
    except Exception:
        return None


def relevance(title, terms):
    """Concern terms match at word starts, not as bare substrings.

    Caught 2026-08-05, the day the unsloth tracker joined the sources: the
    term "slot" substring-matched inside the word "Unsloth", flagging every
    title that names the org, including a celebration post. Left boundary
    only, because several terms are deliberate stems (truncat, think) that
    must keep matching their continuations.
    """
    t = title.lower()
    return sorted({x for x in terms if re.search(r"\b" + re.escape(x), t)})


def hf_discussions(repo, terms):
    d, _ = get_json(f"{HF_API}/models/{repo}/discussions")
    if not d:
        return None
    out = []
    for x in d.get("discussions", []):
        out.append({
            "src": "hf", "repo": repo, "id": x["num"],
            "kind": "pr" if x.get("isPullRequest") else "issue",
            "state": x.get("status", ""), "comments": x.get("numComments", 0),
            "date": (x.get("createdAt") or "")[:10],
            "title": (x.get("title") or "").strip(),
        })
        out[-1]["hits"] = relevance(out[-1]["title"], terms)
    return out


def hf_commits(repo, n=6):
    d, _ = get_json(f"{HF_API}/models/{repo}/commits/main")
    if not d:
        return None
    rows = d if isinstance(d, list) else d.get("commits", [])
    return [{"id": str(c.get("id", ""))[:12], "date": str(c.get("date", ""))[:10],
             "title": str(c.get("title", "")).strip()} for c in rows[:n]]


def gh_issues(repo, term, terms, per_page=15, extra=""):
    q = f"repo:{repo}+{urllib.parse.quote(term)}+in:title{extra}"
    d = gh(f"search/issues?q={q}&per_page={per_page}&sort=updated")
    if not d:
        return None
    out = []
    for i in d.get("items", []):
        row = {
            "src": "gh", "repo": repo, "id": i["number"],
            "kind": "pr" if i.get("pull_request") else "issue",
            "state": i.get("state", ""), "comments": i.get("comments", 0),
            "date": (i.get("updated_at") or "")[:10],
            "title": (i.get("title") or "").strip(),
        }
        row["hits"] = relevance(row["title"], terms)
        out.append(row)
    return out, d.get("total_count", 0)


def probe_docs(base):
    """llms-full.txt, then llms.txt, then decline. Never scrape around a gate."""
    for suffix in ("/llms-full.txt", "/llms.txt"):
        url = base.rstrip("/") + suffix
        req = urllib.request.Request(url, headers={"User-Agent": UA},
                                     method="HEAD")
        try:
            with urllib.request.urlopen(req, timeout=20) as r:
                if r.status == 200:
                    return {"url": url, "status": "available"}
        except Exception:
            continue
    return {"url": base, "status": "declined, no llms.txt surface"}


def render(model, cfg, data):
    L = [GEN_BEGIN, "",
         f"## What the field knows, refreshed {data['refreshed']}", ""]
    L += ["Sorted by source tier. A row is a title, not a thread: fetch a body "
          "with `community.py thread <src> <repo>#<id>` only when it matters.", ""]

    for block in data["blocks"]:
        L += [f"### {block['label']}  (tier {block['tier']})", ""]
        if block.get("error"):
            L += [f"**Unreachable.** {block['error']}. Reported as unknown "
                  "rather than clean.", ""]
            continue
        rows = block["rows"]
        if not rows:
            L += ["Nothing matched.", ""]
            continue
        if block.get("total"):
            L += [f"{block['total']} total matches upstream, {len(rows)} most "
                  "recently updated shown.", ""]
        flagged = [r for r in rows if r["hits"]]
        if flagged:
            L += ["**Matching a concern we have actually paid for:**", ""]
            for r in flagged:
                L.append(f"- `{r['state']}` #{r['id']} ({r['comments']}c, "
                         f"{r['date']}) {r['title']}  "
                         f"<sub>{', '.join(r['hits'])}</sub>")
            L.append("")
        rest = [r for r in rows if not r["hits"]]
        if rest:
            L += ["Other recent:", ""]
            for r in rest:
                L.append(f"- `{r['state']}` #{r['id']} ({r['comments']}c, "
                         f"{r['date']}) {r['title']}")
            L.append("")

    if data.get("commits"):
        L += ["### Upstream commit history", "",
              "Authoritative even where the discussion tab is not.", ""]
        for c in data["commits"]:
            L.append(f"- `{c['id']}` {c['date']}  {c['title']}")
        L.append("")

    if data.get("docs"):
        d = data["docs"]
        L += ["### Documentation surface", "",
              f"- {d['status']}: {d['url']}", ""]

    L += [GEN_END, ""]
    return "\n".join(L)


def write_dossier(model, body):
    DOSSIERS.mkdir(parents=True, exist_ok=True)
    path = DOSSIERS / f"{model}.md"
    if path.exists():
        old = path.read_text()
        if GEN_BEGIN in old and GEN_END in old:
            head = old.split(GEN_BEGIN)[0]
            tail = old.split(GEN_END, 1)[1]
            path.write_text(head + body + tail)
            return path, "updated"
        path.write_text(old.rstrip() + "\n\n" + body)
        return path, "appended"
    path.write_text(TEMPLATE.format(model=model, generated=body))
    return path, "created"


def cmd_collect(only=None):
    src = tomllib.loads(SOURCES.read_text())
    watch = tomllib.loads(WATCHLIST.read_text()).get("model", {})
    terms = src["defaults"]["concern_terms"]
    stacks = src.get("stack", {})
    stamp = subprocess.run(["date", "-I"], capture_output=True,
                           text=True).stdout.strip()

    models = {k: v for k, v in src.get("model", {}).items()
              if not only or k == only}
    if not models:
        print(f"no such model in sources.toml: {only}")
        return 1

    for model, cfg in models.items():
        blocks, commits, docs = [], None, None
        print(f"=== {model}")

        for sname in cfg.get("stacks", []):
            st = stacks.get(sname)
            if not st:
                continue
            for term in cfg.get("github_terms", [])[:2]:
                res = gh_issues(st["github"], term, terms)
                if res is None:
                    blocks.append({"label": f"{st['github']} `{term}`",
                                   "tier": st["tier"],
                                   "error": "github search failed"})
                    print(f"  gh {st['github']} {term}: UNREACHABLE")
                    continue
                rows, total = res
                blocks.append({"label": f"{st['github']} `{term}`",
                               "tier": st["tier"], "rows": rows, "total": total})
                print(f"  gh {st['github']} {term}: {total} total, "
                      f"{sum(1 for r in rows if r['hits'])} flagged")

        repo = (watch.get(model) or {}).get("repo")
        if repo:
            rows = hf_discussions(repo, terms)
            if rows is None:
                blocks.append({"label": f"huggingface {repo}",
                               "tier": cfg.get("hf_tier", 3),
                               "error": "hf discussions unreachable"})
                print(f"  hf {repo}: UNREACHABLE")
            else:
                blocks.append({"label": f"huggingface {repo}",
                               "tier": cfg.get("hf_tier", 3), "rows": rows})
                print(f"  hf {repo}: {len(rows)} discussions, "
                      f"{sum(1 for r in rows if r['hits'])} flagged")
            commits = hf_commits(repo)

        if cfg.get("docs"):
            docs = probe_docs(cfg["docs"])
            print(f"  docs {cfg['docs']}: {docs['status']}")

        # Dedupe across blocks. Two search terms for the same vessel return
        # heavily overlapping issues (gemma-4-26B and 26B-A4B shared 6 of 10),
        # and paying tokens twice for the same row is exactly the waste this
        # instrument exists to remove. First block to claim a row keeps it.
        blocks.sort(key=lambda b: b["tier"])
        claimed, dropped = set(), 0
        for b in blocks:
            if b.get("error"):
                continue
            keep = []
            for r in b["rows"]:
                k = (r["src"], r["repo"], r["id"])
                if k in claimed:
                    dropped += 1
                    continue
                claimed.add(k)
                keep.append(r)
            b["rows"] = keep
        if dropped:
            print(f"  deduped {dropped} rows already listed under another term")
        body = render(model, cfg, {"refreshed": stamp, "blocks": blocks,
                                   "commits": commits, "docs": docs})
        path, how = write_dossier(model, body)
        print(f"  {how} {path.relative_to(HERE.parents[2])}")
    return 0


def cmd_stub():
    """A pointer beside the weights, not the documentation itself.

    The operator asked for the notes to live inside the model folder structure.
    The weights live under the storage `models` concern, which is declared
    re-fetchable from upstream: loss costs bandwidth rather than history. A
    hand-written lab note is not re-fetchable, and filing it there would put
    authored work under the one concern we have declared disposable, outside git
    entirely. So the writing lives in the repo and this drops the signpost.
    """
    watch = tomllib.loads(WATCHLIST.read_text()).get("model", {})
    src = tomllib.loads(SOURCES.read_text()).get("model", {})
    n = 0
    for model in src:
        path = (watch.get(model) or {}).get("path")
        if not path or not Path(path).is_dir():
            print(f"  skip {model}: no local path on this node")
            continue
        dest = Path(path) / "NOTES.md"
        dest.write_text(
            f"# {model}\n\n"
            f"Lab documentation and community notes for this vessel live in the\n"
            f"repo, not here:\n\n"
            f"    ops/zoo/dossiers/{model}.md\n\n"
            f"They are kept there because this directory is the storage\n"
            f"`models` concern, which is declared re-fetchable from upstream.\n"
            f"Weights can be pulled again. A lab note cannot, so it lives\n"
            f"somewhere versioned and backed by two remotes.\n\n"
            f"Refresh with: python3 ops/zoo/community.py collect\n")
        n += 1
        print(f"  wrote {dest}")
    print(f"{n} stubs written")
    return 0


def cmd_thread(source, ref):
    """One body, on demand. The whole point is that this is not done in bulk."""
    if "#" not in ref:
        print("ref must be repo#id, for example ggml-org/llama.cpp#24132")
        return 1
    repo, num = ref.rsplit("#", 1)
    if source == "gh":
        d = gh(f"repos/{repo}/issues/{num}")
        if not d:
            print("unreachable")
            return 1
        print(f"# {d['title']}\n\n`{d['state']}` #{num}, {d.get('comments',0)} comments\n")
        print((d.get("body") or "")[:4000])
        c = gh(f"repos/{repo}/issues/{num}/comments?per_page=20") or []
        for x in c:
            print(f"\n--- {x['user']['login']} {x['created_at'][:10]}")
            print((x.get("body") or "")[:1500])
    else:
        d, _ = get_json(f"{HF_API}/models/{repo}/discussions/{num}")
        if not d:
            print("unreachable")
            return 1
        print(f"# {d.get('title')}\n")
        for e in (d.get("events") or [])[:20]:
            if e.get("type") == "comment":
                who = (e.get("author") or {}).get("name", "?")
                txt = ((e.get("data") or {}).get("latest") or {}).get("raw", "")
                print(f"\n--- {who}\n{txt[:1500]}")
    return 0


HW_TEMPLATE = """# Hardware: {label}

Outstanding upstream issues against silicon this fabric actually runs, plus our
own notes. Generated half is refreshed by `tools/zoo/community.py hardware`;
everything outside the generated block is hand-written and preserved.

**Nodes affected:** {nodes}

{note}

Floor: DMF. No em dashes, no ellipses.

## Lab notes, ours

_Nothing recorded yet. What we have learned running this silicon: the flags it
needs, the builds that work, the things that bit us._

## For upstream

_What we know that the field does not. Nothing queued yet._

{generated}
"""


def cmd_hardware(only=None):
    """Open issues only, against our actual silicon.

    The question here is what is CURRENTLY broken that could bite this fleet,
    not what has ever been wrong, so every search carries state:open. Closed
    issues are history; the model dossiers keep those because a closed bug still
    explains a behaviour we might be seeing on an older build.
    """
    src = tomllib.loads(SOURCES.read_text())
    terms = src["defaults"]["concern_terms"]
    stacks = src.get("stack", {})
    stamp = subprocess.run(["date", "-I"], capture_output=True,
                           text=True).stdout.strip()

    targets = {k: v for k, v in src.get("hardware", {}).items()
               if not only or k == only}
    if not targets:
        print(f"no such hardware target: {only}")
        return 1

    for key, cfg in targets.items():
        print(f"=== {key}: {cfg['label']}")
        blocks = []
        for sname in cfg.get("stacks", []):
            st = stacks.get(sname)
            if not st:
                continue
            for term in cfg.get("terms", []):
                res = gh_issues(st["github"], term, terms, extra="+state:open")
                if res is None:
                    blocks.append({"label": f"{st['github']} `{term}`",
                                   "tier": st["tier"],
                                   "error": "github search failed"})
                    print(f"  {st['github']} {term}: UNREACHABLE")
                    continue
                rows, total = res
                blocks.append({"label": f"{st['github']} `{term}` (open)",
                               "tier": st["tier"], "rows": rows, "total": total})
                print(f"  {st['github']} {term}: {total} open, "
                      f"{sum(1 for r in rows if r['hits'])} flagged")

        blocks.sort(key=lambda b: b["tier"])
        claimed, dropped = set(), 0
        for b in blocks:
            if b.get("error"):
                continue
            keep = []
            for r in b["rows"]:
                k = (r["src"], r["repo"], r["id"])
                if k in claimed:
                    dropped += 1
                    continue
                claimed.add(k)
                keep.append(r)
            b["rows"] = keep
        if dropped:
            print(f"  deduped {dropped} rows already listed under another term")

        body = render(key, cfg, {"refreshed": stamp, "blocks": blocks,
                                 "commits": None, "docs": None})
        DOSSIERS.mkdir(parents=True, exist_ok=True)
        path = DOSSIERS / f"_hw_{key}.md"
        if path.exists():
            old = path.read_text()
            head, tail = old.split(GEN_BEGIN)[0], old.split(GEN_END, 1)[1]
            path.write_text(head + body + tail)
            how = "updated"
        else:
            path.write_text(HW_TEMPLATE.format(
                label=cfg["label"], nodes=", ".join(cfg.get("nodes", [])),
                note=cfg.get("note", ""), generated=body))
            how = "created"
        print(f"  {how} {path.name}")
    return 0


def main():
    ap = argparse.ArgumentParser(description="Community notes for the zoo")
    ap.add_argument("mode", choices=["collect", "hardware", "stub", "thread"])
    ap.add_argument("args", nargs="*")
    ap.add_argument("--model")
    a = ap.parse_args()
    if a.mode == "collect":
        return cmd_collect(a.model)
    if a.mode == "hardware":
        return cmd_hardware(a.model)
    if a.mode == "stub":
        return cmd_stub()
    if len(a.args) != 2:
        ap.error("thread needs <gh|hf> <repo#id>")
    return cmd_thread(a.args[0], a.args[1])


if __name__ == "__main__":
    raise SystemExit(main())
